version: 2

build:
  os: ubuntu-20.04
  tools:
    # Keep version in sync with tox.ini (docs and gh-actions).
    python: "3.10"

python:
  install:
    - path: .
      method: pip
    - requirements: "docs/requirements.txt"
