version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    # Keep version in sync with tox.ini (docs and gh-actions).
    python: "3.11"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv tool install rust-just
    # Need the tags to calculate the version
    install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs --all-extras --link-mode=copy
    post_install:
      - git fetch --tags
    build:
      html:
        - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH /home/docs/.local/bin/just docs $READTHEDOCS_OUTPUT